### ISSUE TITLE
Go 1.0?!

### ISSUE THREAD

**Issue by phated** [js-cli/js-interpret#37]
I think we are at a point where we could go 1.0 - @tkellen Thoughts?

We might want to tackle #36 first.

**Comment by blakeembrey** [comment]
If you're going to `1.0`, I'd kill `typescript-node` and `typescript-register` from `.ts` and `.tsx` support.

Reference: https://github.com/pspeter3/typescript-register

I'd probably say kill `typescript-require` too, but that is ongoing (no fixes or resolution yet): https://github.com/theblacksmith/typescript-require/issues/36

**Comment by phated** [comment]
I'm fine with either but maybe we let people keep using old versions for the time being.  I wouldn't want to remove babel/register or babel-core/register just because we added babel-register because people might still be using older versions.

**Comment by blakeembrey** [comment]
No worries, was just mentioning since 1.0 is a breaking change. Just won't be able to remove them until 2.0.

**Comment by phated** [comment]
I think we should keep them through the 1.0 lifecycle.  If this module starts to get huge, we can remove and bump 2.0

**Comment by phated** [comment]
Done and published!
